services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - backend_network
  db:
    image: postgres:latest
    env_file:
      - .env.dblocal
    ports:
      - "5432:5432"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
