swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth/google/login:
        get:
            tags:
                - Auth
            summary: Google login Auth
            description: Initiates the Google OAuth 2.0 login flow by redirecting to the Google authorization endpoint.
            operationId: Auth#Google login
            responses:
                "307":
                    description: Temporary Redirect response.
            schemes:
                - http
    /auth/google/logout:
        get:
            tags:
                - Auth
            summary: Google logout Auth
            description: Logs the user out by clearing the session and redirecting to the appropriate post-logout URL.
            operationId: Auth#Google logout
            responses:
                "307":
                    description: Temporary Redirect response.
            schemes:
                - http
    /auth/me:
        get:
            tags:
                - Auth
            summary: Me Auth
            description: Returns information about the currently authenticated user.
            operationId: Auth#Me
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AccountUser'
                        required:
                            - id
                            - email
                            - firstName
                            - lastNames
                            - remainingNames
                            - attendeeGroupName
                            - attendeeGroupPriority
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/AccountUser'
                        required:
                            - id
                            - email
                            - firstName
                            - lastNames
                            - remainingNames
                            - attendeeGroupName
                            - attendeeGroupPriority
            schemes:
                - http
    /enrollment:
        put:
            tags:
                - enrollment
            summary: update_enrollment enrollment
            description: Actualizar el estado de una inscripción
            operationId: enrollment#update_enrollment
            parameters:
                - name: update_enrollment_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UpdateEnrollmentPayload'
                    required:
                        - attendee_id
                        - course_id
                        - passed
            responses:
                "200":
                    description: OK response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/EnrollmentUpdateEnrollmentNotFoundResponseBody'
            schemes:
                - http
        post:
            tags:
                - enrollment
            summary: enroll enrollment
            description: Inscribir un asistente en un curso
            operationId: enrollment#enroll
            parameters:
                - name: EnrollRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/EnrollmentPayload'
                    required:
                        - attendee_id
                        - course_id
                        - passed
            responses:
                "201":
                    description: Created response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/EnrollmentEnrollBadRequestResponseBody'
            schemes:
                - http
    /enrollment/{attendee_id}/{course_id}:
        delete:
            tags:
                - enrollment
            summary: delete_enrollment enrollment
            description: Eliminar una inscripción de un asistente en un curso
            operationId: enrollment#delete_enrollment
            parameters:
                - name: attendee_id
                  in: path
                  description: ID del asistente
                  required: true
                  type: integer
                  format: int32
                - name: course_id
                  in: path
                  description: ID del curso
                  required: true
                  type: integer
                  format: int32
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/EnrollmentDeleteEnrollmentNotFoundResponseBody'
            schemes:
                - http
    /enrollment/course/{course_id}/users:
        get:
            tags:
                - enrollment
            summary: list_enrolled_users enrollment
            description: Listar usuarios inscritos en un curso
            operationId: enrollment#list_enrolled_users
            parameters:
                - name: course_id
                  in: path
                  description: ID del curso
                  required: true
                  type: integer
                  format: int32
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/EnrolledUser'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/EnrollmentListEnrolledUsersNotFoundResponseBody'
            schemes:
                - http
    /google/callback:
        get:
            tags:
                - Auth
            summary: GoogleCallback Auth
            description: Google OAuth callback. Creates or reuses a session and redirects to the frontend.
            operationId: Auth#GoogleCallback
            responses:
                "307":
                    description: Temporary Redirect response.
                "401":
                    description: Unauthorized response.
            schemes:
                - http
definitions:
    AccountUser:
        title: AccountUser
        type: object
        properties:
            attendeeGroupName:
                type: string
                description: User attendee group name
                example: Et non sapiente itaque.
            attendeeGroupPriority:
                type: string
                description: User attendee group priority
                example: Assumenda itaque aspernatur nam quis ratione et.
            email:
                type: string
                description: User email
                example: Eaque velit nobis ut ab.
            firstName:
                type: string
                description: User first name
                example: Excepturi rerum perspiciatis laboriosam voluptas eaque.
            id:
                type: string
                description: Unique user ID
                example: Qui veritatis exercitationem ut aut iusto.
            lastNames:
                type: string
                description: User last names
                example: Doloribus eveniet voluptates.
            remainingNames:
                type: string
                description: User remaining names
                example: Ducimus excepturi eligendi et necessitatibus autem aut.
        example:
            attendeeGroupName: Non nihil est eius.
            attendeeGroupPriority: Reiciendis quisquam consequatur quia voluptatem.
            email: In quis eligendi ipsam aut.
            firstName: Modi quis sequi eum hic facere accusamus.
            id: Tenetur ipsam.
            lastNames: Commodi ab voluptas sed.
            remainingNames: Quibusdam aut.
        required:
            - id
            - email
            - firstName
            - lastNames
            - remainingNames
            - attendeeGroupName
            - attendeeGroupPriority
    EnrolledUser:
        title: EnrolledUser
        type: object
        properties:
            email:
                type: string
                example: aurelia@daniel.name
                format: email
            first_name:
                type: string
                example: Et sunt quisquam.
            last_names:
                type: string
                example: Tenetur accusamus et deleniti non nihil animi.
            remaining_names:
                type: string
                example: Voluptatem aperiam cupiditate.
        description: Datos de usuario inscrito
        example:
            email: jayda@adams.com
            first_name: Nesciunt ex recusandae expedita explicabo inventore rerum.
            last_names: Necessitatibus sed magni est omnis qui.
            remaining_names: Non excepturi.
        required:
            - first_name
            - last_names
            - email
    EnrollmentDeleteEnrollmentNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: No se encontró el recurso (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollmentEnrollBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Petición inválida (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollmentListEnrolledUsersNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: list_enrolled_users_not_found_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EnrollmentPayload:
        title: EnrollmentPayload
        type: object
        properties:
            attendee_id:
                type: integer
                description: ID del asistente
                example: 466223378
                format: int32
            course_id:
                type: integer
                description: ID del curso
                example: 1391554063
                format: int32
            passed:
                type: boolean
                description: Si el curso fue aprobado
                example: false
        example:
            attendee_id: 921510809
            course_id: 2146821637
            passed: false
        required:
            - attendee_id
            - course_id
            - passed
    EnrollmentUpdateEnrollmentNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: No se encontró el recurso (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UpdateEnrollmentPayload:
        title: UpdateEnrollmentPayload
        type: object
        properties:
            attendee_id:
                type: integer
                description: ID del asistente
                example: 828113516
                format: int32
            course_id:
                type: integer
                description: ID del curso
                example: 1124555278
                format: int32
            passed:
                type: boolean
                description: Nuevo estado aprobado
                example: false
        example:
            attendee_id: 571486384
            course_id: 1992032917
            passed: true
        required:
            - attendee_id
            - course_id
            - passed
